"use strict";

/**
 * Guided tour definitions.
 *
 * A tour is not a tooltip carousel. Each step names a DOM target, the action
 * the user must take, and — where the step collects a value — what to ask and
 * how to validate the answer. The frontend tour engine drives the real UI:
 * it navigates, highlights, waits for the element to exist, fills the field
 * with the user's answer, and only advances when the step's completion
 * condition is met.
 *
 * That is why these live on the server: the same definition drives the
 * assistant's intent matching, the help centre article, and the interactive
 * walkthrough, and a tour can be corrected without shipping a frontend build.
 *
 * Step contract
 *   target        CSS selector, matched by [data-tour="..."] in the app
 *   action        navigate | click | input | select | toggle | wait | observe
 *   ask           question shown in the assistant panel (input steps)
 *   field         which form field the answer is written into
 *   validate      { type, min, max, required, pattern, message }
 *   completeWhen  urlMatches | elementVisible | elementGone | valueSet | manual
 */

/**
 * Month numbers as the payroll screen's own Month select renders them, so the
 * walkthrough offers exactly the choices the field behind it accepts.
 */
const MONTHS = Array.from({ length: 12 }, (_, index) => ({
  value: index + 1,
  label: new Date(Date.UTC(2000, index, 1)).toLocaleString("en", { month: "long", timeZone: "UTC" }),
}));

const TOURS = [
  {
    id: "create_leave_policy",
    title: "Create a leave policy",
    description: "Set up leave types, how many days people get, and who approves.",
    category: "leave",
    permission: "leave.manage_policies",
    estimatedMinutes: 4,
    steps: [
      {
        id: "navigate",
        action: "navigate",
        route: "/app/settings/leave",
        title: "Opening leave policies",
        body: "Settings → Leave → Policies is where every leave rule lives.",
        completeWhen: "urlMatches",
      },
      {
        id: "click_create",
        action: "click",
        target: '[data-tour="leave-policy-create"]',
        title: "Start a new policy",
        body: "Select **New policy**.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="leave-policy-form"]',
      },
      {
        id: "enter_name",
        action: "input",
        target: '[data-tour="leave-policy-name"]',
        field: "name",
        title: "Name the policy",
        ask: "What should this policy be called?",
        placeholder: "e.g. General Staff Policy",
        validate: { type: "text", required: true, min: 2, max: 60, message: "Give the policy a name of at least 2 characters" },
        body: "Give it a name your HR team will recognise. Companies usually have two or three: staff, workers, and interns.",
        completeWhen: "valueSet",
      },
      {
        id: "enter_code",
        action: "input",
        target: '[data-tour="leave-policy-code"]',
        field: "code",
        title: "Give it a short code",
        ask: "A short code for this policy?",
        placeholder: "e.g. STAFF",
        validate: { type: "text", required: true, max: 20 },
        completeWhen: "valueSet",
      },
      {
        id: "add_leave_type",
        action: "click",
        target: '[data-tour="leave-policy-add-rule"]',
        title: "Pick your first leave type",
        body: "Click the leave type you want to configure. Each type gets its own set of rules inside the policy, so you can give casual leave and earned leave completely different behaviour.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="leave-rule-row"]',
      },
      {
        id: "enter_days",
        action: "input",
        target: '[data-tour="leave-rule-days"]',
        field: "rules.0.allocation.daysPerPeriod",
        title: "How many days a year?",
        ask: "How many days of this leave should employees get each year?",
        placeholder: "e.g. 12",
        validate: { type: "number", required: true, min: 0, max: 365, message: "Enter a number between 0 and 365" },
        body: "This is the annual entitlement. If you credit leave monthly instead, you can change the allocation mode in the next step.",
        completeWhen: "valueSet",
      },
      {
        id: "allocation_mode",
        action: "select",
        target: '[data-tour="leave-rule-allocation-mode"]',
        field: "rules.0.allocation.mode",
        title: "When is it credited?",
        ask: "Should the full year be credited up front, or accrue monthly?",
        options: [
          { value: "annual", label: "All at once, at the start of the year" },
          { value: "monthly", label: "Credited every month" },
          { value: "accrual", label: "Earned per completed month of service" },
        ],
        completeWhen: "valueSet",
      },
      {
        id: "carry_forward",
        action: "toggle",
        target: '[data-tour="leave-rule-carry-forward"]',
        field: "rules.0.carryForward.enabled",
        title: "Carry forward unused leave?",
        ask: "Can employees carry unused days into next year?",
        options: [
          { value: true, label: "Yes, carry forward" },
          { value: false, label: "No, unused days lapse" },
        ],
        completeWhen: "valueSet",
      },
      {
        id: "sandwich_rule",
        action: "select",
        target: '[data-tour="leave-rule-weekly-offs"]',
        field: "rules.0.counting.weeklyOffs",
        title: "Weekends inside a leave",
        ask: "If someone takes leave across a weekend, should the weekend be deducted?",
        options: [
          { value: "exclude", label: "No — only working days count" },
          { value: "sandwich", label: "Only if leave falls on both sides (sandwich rule)" },
          { value: "include", label: "Yes — every calendar day counts" },
        ],
        body: "This is the single rule employees notice most. The sandwich option deducts a weekend only when it is surrounded by leave.",
        completeWhen: "valueSet",
      },
      {
        id: "save",
        action: "click",
        target: '[data-tour="leave-policy-save"]',
        title: "Save the policy",
        body: "Review the summary and save. You can add more leave types to this policy at any time.",
        completeWhen: "elementGone",
        completeTarget: '[data-tour="leave-policy-form"]',
      },
      {
        id: "done",
        action: "observe",
        title: "Policy created",
        body: "Assign it to employees from their profile, or set it as the default so every new joiner gets it automatically.",
        completeWhen: "manual",
      },
    ],
  },

  {
    id: "add_employee",
    title: "Add an employee",
    description: "Create an employee record and optionally invite them to the portal.",
    category: "employee",
    permission: "employee.create",
    estimatedMinutes: 3,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/employees", title: "Opening Employees", completeWhen: "urlMatches" },
      {
        id: "click_add",
        action: "click",
        target: '[data-tour="employee-add"]',
        title: "Start a new employee",
        body: "Select **Add employee**.",
        completeWhen: "urlMatches",
        completeRoute: "/app/employees/new",
      },
      {
        id: "first_name",
        action: "input",
        target: '[data-tour="employee-first-name"]',
        field: "personal.firstName",
        title: "Their name",
        ask: "What is the employee's first name?",
        validate: { type: "text", required: true, max: 60 },
        completeWhen: "valueSet",
      },
      {
        id: "last_name",
        action: "input",
        target: '[data-tour="employee-last-name"]',
        field: "personal.lastName",
        ask: "And their last name?",
        title: "Last name",
        validate: { type: "text", max: 60 },
        completeWhen: "valueSet",
      },
      {
        id: "work_email",
        action: "input",
        target: '[data-tour="employee-work-email"]',
        field: "personal.workEmail",
        title: "Work email",
        ask: "What is their work email address?",
        body: "This is where their portal invitation and payslips will go.",
        validate: { type: "email", message: "Enter a valid email address" },
        completeWhen: "valueSet",
      },
      {
        id: "department",
        action: "select",
        target: '[data-tour="employee-department"]',
        field: "employment.departmentId",
        title: "Department",
        ask: "Which department do they belong to?",
        optionsFrom: "/departments",
        completeWhen: "valueSet",
      },
      {
        id: "designation",
        action: "select",
        target: '[data-tour="employee-designation"]',
        field: "employment.designationId",
        title: "Designation",
        ask: "What is their job title?",
        optionsFrom: "/designations",
        completeWhen: "valueSet",
      },
      {
        id: "joining_date",
        action: "input",
        target: '[data-tour="employee-joining-date"]',
        field: "employment.joiningDate",
        title: "Joining date",
        ask: "When did (or will) they join?",
        validate: { type: "date", required: true },
        body: "Attendance and leave are only calculated from this date onward.",
        completeWhen: "valueSet",
      },
      {
        id: "save",
        action: "click",
        target: '[data-tour="employee-save"]',
        title: "Save",
        body: "The employee code is generated automatically from your numbering settings.",
        completeWhen: "urlMatches",
        completeRoute: "/app/employees/",
      },
    ],
  },

  {
    id: "configure_half_day",
    title: "Configure half-day rules",
    description: "Decide how many hours count as a half day, and when someone is marked absent.",
    category: "attendance",
    permission: "settings.manage_policies",
    estimatedMinutes: 3,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/settings/attendance", title: "Opening attendance policies", completeWhen: "urlMatches" },
      {
        id: "open_policy",
        action: "click",
        target: '[data-tour="attendance-policy-row"]',
        title: "Open your policy",
        body: "Pick the policy you want to change. Most organizations start with one.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="attendance-policy-form"]',
      },
      {
        id: "hours_basis",
        action: "select",
        target: '[data-tour="attendance-hours-basis"]',
        field: "hours.basis",
        title: "How should hours be measured?",
        ask: "Should thresholds be a share of the shift, or fixed hours?",
        options: [
          { value: "shift_based", label: "A percentage of the scheduled shift" },
          { value: "fixed_hours", label: "Fixed hours, regardless of shift" },
        ],
        body: "Shift-based works better when different teams have different shift lengths.",
        completeWhen: "valueSet",
      },
      {
        id: "half_day_threshold",
        action: "input",
        target: '[data-tour="attendance-half-day"]',
        field: "hours.halfDayPercent",
        title: "Half-day threshold",
        ask: "What is the minimum needed for a half day?",
        placeholder: "e.g. 45 (percent) or 240 (minutes)",
        validate: { type: "number", required: true, min: 1 },
        body: "Below this, the day is treated as an absence.",
        completeWhen: "valueSet",
      },
      {
        id: "full_day_threshold",
        action: "input",
        target: '[data-tour="attendance-full-day"]',
        field: "hours.fullDayPercent",
        title: "Full-day threshold",
        ask: "And what counts as a full day?",
        validate: { type: "number", required: true, min: 1 },
        completeWhen: "valueSet",
      },
      {
        id: "late_half_day",
        action: "input",
        target: '[data-tour="attendance-late-half-day"]',
        field: "arrival.halfDayAfterMinutes",
        title: "Arriving very late",
        ask: "How many minutes late should automatically make it a half day?",
        placeholder: "e.g. 240. Use 0 to switch this off.",
        validate: { type: "number", min: 0, max: 720 },
        completeWhen: "valueSet",
      },
      {
        id: "save",
        action: "click",
        target: '[data-tour="attendance-policy-save"]',
        title: "Save the policy",
        body: "Existing attendance is not changed automatically. Use **Recalculate** if you want the new rules applied to past days.",
        completeWhen: "elementGone",
        completeTarget: '[data-tour="attendance-policy-form"]',
      },
    ],
  },

  {
    id: "connect_biometric_device",
    title: "Connect a biometric device",
    description: "Add an attendance device and pull punches from it.",
    category: "biometric",
    permission: "biometric.manage",
    estimatedMinutes: 5,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/settings/biometric", title: "Opening biometric devices", completeWhen: "urlMatches" },
      {
        id: "add_device",
        action: "click",
        target: '[data-tour="device-add"]',
        title: "Add a device",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="device-form"]',
      },
      {
        id: "choose_provider",
        action: "select",
        target: '[data-tour="device-provider"]',
        field: "provider",
        title: "How will it connect?",
        ask: "How does this device reach us?",
        optionsFrom: "/biometric/providers",
        body: "Devices on your office LAN cannot be reached from the cloud directly — choose Webhook or File import for those, or install the LAN bridge.",
        completeWhen: "valueSet",
      },
      {
        id: "device_name",
        action: "input",
        target: '[data-tour="device-name"]',
        field: "name",
        title: "Name the device",
        ask: "What should we call this device?",
        placeholder: "e.g. Main Gate Reader",
        validate: { type: "text", required: true, max: 60 },
        completeWhen: "valueSet",
      },
      {
        id: "device_code",
        action: "input",
        target: '[data-tour="device-code"]',
        field: "code",
        title: "Device code",
        ask: "A short code for this device?",
        placeholder: "e.g. GATE1",
        validate: { type: "text", required: true, max: 20 },
        completeWhen: "valueSet",
      },
      {
        id: "location",
        action: "select",
        target: '[data-tour="device-location"]',
        field: "locationId",
        title: "Where is it?",
        ask: "Which work location is this device at?",
        optionsFrom: "/locations",
        body: "The location decides which timezone the device's clock is read in.",
        completeWhen: "valueSet",
      },
      {
        id: "test",
        action: "click",
        target: '[data-tour="device-test"]',
        title: "Test the connection",
        body: "Nothing is imported yet — this only checks that we can reach the device.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="device-test-result"]',
      },
      {
        id: "save",
        action: "click",
        target: '[data-tour="device-save"]',
        title: "Save",
        completeWhen: "elementGone",
        completeTarget: '[data-tour="device-form"]',
      },
      {
        id: "map_ids",
        action: "observe",
        title: "One more thing: employee IDs",
        body:
          "Each employee's **Biometric ID** must match their enrolment number on the device. Punches from an unknown ID are stored as *unmapped* — set the ID later and use **Reprocess** to bring that attendance back.",
        completeWhen: "manual",
      },
    ],
  },

  {
    id: "run_payroll",
    title: "Run payroll",
    description: "Create a payroll run, review it, approve, and publish payslips.",
    category: "payroll",
    permission: "payroll.process",
    estimatedMinutes: 6,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/payroll", title: "Opening payroll runs", completeWhen: "urlMatches" },
      {
        id: "check_attendance",
        action: "observe",
        title: "Before you start",
        body:
          "Payroll reads attendance — it does not recalculate it. Make sure the month's attendance is processed and any corrections are approved first.",
        completeWhen: "manual",
      },
      {
        id: "create_run",
        action: "click",
        target: '[data-tour="payroll-run-create"]',
        title: "Create a run",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="payroll-run-form"]',
      },
      {
        id: "choose_period",
        action: "select",
        target: '[data-tour="payroll-run-period"]',
        field: "month",
        title: "Which month?",
        ask: "Which month are you paying for?",
        // The same twelve values the real control offers. A select step with
        // neither `options` nor `optionsFrom` renders an empty dropdown, and a
        // required empty dropdown can never be satisfied — with no Skip button
        // on an input step, that left the payroll walkthrough with no way
        // forward at all.
        options: MONTHS,
        validate: { required: true },
        completeWhen: "valueSet",
      },
      {
        id: "process",
        action: "click",
        target: '[data-tour="payroll-run-process"]',
        title: "Calculate",
        body: "This runs in the background. Large organizations take a minute or two.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="payroll-run-items"]',
      },
      {
        id: "review",
        action: "observe",
        title: "Review before approving",
        body:
          "Check the exceptions list first. Anyone with no salary assigned, or with unusually low payable days, appears there.",
        completeWhen: "manual",
      },
      {
        id: "approve",
        action: "click",
        target: '[data-tour="payroll-run-approve"]',
        title: "Approve",
        body: "Approval is recorded against your name in the audit trail.",
        completeWhen: "manual",
      },
      {
        id: "publish",
        action: "click",
        target: '[data-tour="payroll-run-publish"]',
        title: "Publish payslips",
        body: "Employees are notified and can download their payslip from the portal. Published payslips are frozen — a later recalculation cannot change them.",
        completeWhen: "manual",
      },
    ],
  },

  {
    id: "change_company_logo",
    title: "Change your company logo",
    description: "Upload a logo used across the app, emails and documents.",
    category: "settings",
    permission: "settings.manage_branding",
    estimatedMinutes: 2,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/settings/branding", title: "Opening branding", completeWhen: "urlMatches" },
      {
        id: "upload",
        action: "click",
        target: '[data-tour="branding-logo-upload"]',
        title: "Upload your logo",
        body: "PNG or SVG with a transparent background works best. Around 400×120 is ideal.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="branding-logo-preview"]',
      },
      {
        id: "colours",
        action: "observe",
        title: "Set your colours",
        body:
          "The primary colour drives buttons, links and highlights across the whole app, plus your email headers and PDF accents.",
        completeWhen: "manual",
      },
      {
        id: "save",
        action: "click",
        target: '[data-tour="branding-save"]',
        title: "Save",
        completeWhen: "manual",
      },
    ],
  },

  {
    id: "create_shift",
    title: "Create a shift",
    description: "Define working hours, including night shifts that cross midnight.",
    category: "attendance",
    permission: "shift.manage",
    estimatedMinutes: 2,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/settings/shifts", title: "Opening shifts", completeWhen: "urlMatches" },
      { id: "add", action: "click", target: '[data-tour="shift-add"]', title: "Add a shift", completeWhen: "elementVisible", completeTarget: '[data-tour="shift-form"]' },
      {
        id: "name",
        action: "input",
        target: '[data-tour="shift-name"]',
        field: "name",
        title: "Name",
        ask: "What is this shift called?",
        placeholder: "e.g. General, Night",
        validate: { type: "text", required: true },
        completeWhen: "valueSet",
      },
      {
        id: "start",
        action: "input",
        target: '[data-tour="shift-start"]',
        field: "startTime",
        title: "Start time",
        ask: "When does the shift start?",
        placeholder: "HH:mm, e.g. 09:00",
        validate: { type: "time", required: true },
        completeWhen: "valueSet",
      },
      {
        id: "end",
        action: "input",
        target: '[data-tour="shift-end"]',
        field: "endTime",
        title: "End time",
        ask: "And when does it end?",
        placeholder: "HH:mm, e.g. 18:00",
        validate: { type: "time", required: true },
        body: "If the end time is before the start time, we treat it as a night shift that ends the next day — you do not need to configure anything else.",
        completeWhen: "valueSet",
      },
      {
        id: "break",
        action: "input",
        target: '[data-tour="shift-break"]',
        field: "breakMinutes",
        title: "Break",
        ask: "How long is the unpaid break, in minutes?",
        validate: { type: "number", min: 0, max: 480 },
        completeWhen: "valueSet",
      },
      { id: "save", action: "click", target: '[data-tour="shift-save"]', title: "Save", completeWhen: "elementGone", completeTarget: '[data-tour="shift-form"]' },
    ],
  },

  {
    id: "import_employees",
    title: "Import employees from a spreadsheet",
    description: "Bring your existing employee list in from CSV or Excel.",
    category: "employee",
    permission: "employee.import",
    estimatedMinutes: 6,
    steps: [
      { id: "navigate", action: "navigate", route: "/app/employees/import", title: "Opening the importer", completeWhen: "urlMatches" },
      {
        id: "download_template",
        action: "click",
        target: '[data-tour="import-template"]',
        title: "Start from the template",
        body: "The template already includes any custom fields you have created, and a sheet explaining every column.",
        completeWhen: "manual",
      },
      {
        id: "prepare",
        action: "observe",
        title: "Before you upload",
        body:
          "Departments, designations and locations must already exist — the file refers to them by code. Create those first if you have not.",
        completeWhen: "manual",
      },
      {
        id: "upload",
        action: "click",
        target: '[data-tour="import-upload"]',
        title: "Upload your file",
        body: "Nothing is saved yet. We only read the columns.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="import-mapping"]',
      },
      {
        id: "map",
        action: "observe",
        title: "Check the column mapping",
        body: "We guess the mapping from your headers. Correct anything that is wrong before continuing.",
        completeWhen: "manual",
      },
      {
        id: "validate",
        action: "click",
        target: '[data-tour="import-validate"]',
        title: "Validate",
        body: "Every problem row is listed with the reason. Nothing has been written yet.",
        completeWhen: "elementVisible",
        completeTarget: '[data-tour="import-results"]',
      },
      {
        id: "commit",
        action: "click",
        target: '[data-tour="import-commit"]',
        title: "Import",
        body: "Valid rows are created. Rejected rows are reported back so you can fix and re-upload just those.",
        completeWhen: "manual",
      },
    ],
  },
];

const TOURS_BY_ID = Object.fromEntries(TOURS.map((t) => [t.id, t]));

module.exports = { TOURS, TOURS_BY_ID };
