"use strict";

/**
 * Sheet templates seeded into every organization.
 *
 * The same idea as the default letters: a working starting point in the
 * layouts Indian HR and payroll teams actually hand to banks, auditors and
 * labour inspectors, editable column by column.
 */

const col = (key, label, extra = {}) => ({ key, label, width: 16, format: "text", ...extra });
const money = (key, label, extra = {}) => col(key, label, { format: "money", total: true, width: 14, ...extra });
const num = (key, label, extra = {}) => col(key, label, { format: "number", width: 10, ...extra });

const SHEETS = [
  {
    name: "Salary Sheet",
    code: "SALARY_SHEET",
    description: "Monthly salary register for a payroll run — one row per employee, every component.",
    source: "payroll_items",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("designation", "Designation", { width: 18 }),
      col("department", "Department", { width: 16 }),
      num("payableDays", "Payable days"),
      num("lopDays", "LOP"),
      money("BASIC", "Basic"),
      money("HRA", "HRA"),
      money("SPECIAL", "Special allowance"),
      money("gross", "Gross"),
      money("PF", "PF"),
      money("ESI", "ESI"),
      money("PT", "PT"),
      money("TDS", "TDS"),
      money("totalDeductions", "Total deductions"),
      money("net", "Net pay"),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Salary Sheet", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true, signatureLabels: ["Prepared by", "Checked by", "Approved by"] },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Bank Advice",
    code: "BANK_ADVICE",
    description: "Net pay per employee with bank details, in the layout most bank bulk-upload files expect.",
    source: "payroll_items",
    filters: { status: "calculated" },
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("accountHolderName", "Beneficiary name", { width: 26 }),
      col("accountNumber", "Account number", { width: 20 }),
      col("ifscCode", "IFSC", { width: 14 }),
      col("bankName", "Bank", { width: 20 }),
      col("paymentMode", "Mode", { width: 10 }),
      money("net", "Amount"),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Salary Transfer Advice", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true, signatureLabels: ["Authorised signatory"] },
    page: { orientation: "portrait", size: "A4" },
    showRowNumbers: true,
  },
  {
    name: "PF Contribution Register",
    code: "PF_REGISTER",
    description: "Employee and employer PF for a run, with UAN — the input for the ECR file.",
    source: "payroll_items",
    columns: [
      col("uan", "UAN", { width: 14 }),
      col("pfNumber", "PF number", { width: 16 }),
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      money("BASIC", "PF wages"),
      money("PF", "Employee PF"),
      money("PF_EMPLOYER", "Employer PF"),
      money("EPS", "EPS"),
      num("lopDays", "NCP days"),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Provident Fund Contribution Register", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "ESI Register",
    code: "ESI_REGISTER",
    description: "ESI wages and contributions for employees covered under ESI.",
    source: "payroll_items",
    columns: [
      col("esiNumber", "ESI number", { width: 16 }),
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      num("payableDays", "Days"),
      money("gross", "ESI wages"),
      money("ESI", "Employee ESI"),
      money("ESI_EMPLOYER", "Employer ESI"),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "ESI Contribution Register", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Attendance Muster Roll",
    code: "MUSTER_ROLL",
    description: "The classic grid: one row per employee, one column per day, P/A/L/H in each cell.",
    source: "attendance_muster",
    columns: [
      col("employeeCode", "Code", { width: 10 }),
      col("name", "Name", { width: 22 }),
      col("designation", "Designation", { width: 14 }),
      num("present", "P", { width: 5 }),
      num("absent", "A", { width: 5 }),
      num("leave", "L", { width: 5 }),
      num("weeklyOff", "WO", { width: 5 }),
      num("holiday", "H", { width: 5 }),
      num("payableDays", "Payable", { width: 8 }),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Muster Roll", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: false, signatureLabels: ["Timekeeper", "HR", "Authorised signatory"] },
    page: { orientation: "landscape", size: "A3" },
  },
  {
    name: "Monthly Attendance Summary",
    code: "ATTENDANCE_SUMMARY",
    description: "Per-employee totals for a period.",
    source: "attendance_monthly",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      num("present", "Present"),
      num("halfDay", "Half days"),
      num("absent", "Absent"),
      num("leave", "Leave"),
      num("weeklyOff", "Weekly off"),
      num("holiday", "Holidays"),
      num("late", "Late marks"),
      num("payableDays", "Payable days", { total: true }),
      num("overtimeHours", "OT hours", { total: true }),
    ],
    sort: "employeeCode",
    groupBy: "department",
    header: { showCompany: true, title: "Attendance Summary", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Late Arrival Register",
    code: "LATE_REGISTER",
    description: "Every late mark in the period.",
    source: "attendance_daily",
    filters: { status: "present" },
    columns: [
      col("date", "Date", { format: "date", width: 12 }),
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      col("shift", "Shift", { width: 10 }),
      col("checkIn", "In", { width: 8 }),
      num("lateBy", "Late by (min)", { format: "integer" }),
    ],
    sort: "date",
    header: { showCompany: true, title: "Late Arrivals", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: false },
    page: { orientation: "portrait", size: "A4" },
  },
  {
    name: "Overtime Register",
    code: "OT_REGISTER",
    description: "Overtime hours by day, with approval status.",
    source: "attendance_daily",
    columns: [
      col("date", "Date", { format: "date", width: 12 }),
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      col("checkIn", "In", { width: 8 }),
      col("checkOut", "Out", { width: 8 }),
      num("workedHours", "Worked"),
      num("overtimeHours", "OT hours", { total: true }),
      col("overtimeStatus", "OT status", { width: 12 }),
    ],
    sort: "date",
    header: { showCompany: true, title: "Overtime Register", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true, signatureLabels: ["Prepared by", "Approved by"] },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Leave Register",
    code: "LEAVE_REGISTER",
    description: "Leave taken in a period, by employee.",
    source: "leave_requests",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      col("leaveType", "Leave type", { width: 16 }),
      col("fromDate", "From", { format: "date", width: 12 }),
      col("toDate", "To", { format: "date", width: 12 }),
      num("days", "Days", { total: true }),
      col("status", "Status", { width: 10 }),
      col("approver", "Approved by", { width: 18 }),
    ],
    sort: "fromDate",
    header: { showCompany: true, title: "Leave Register", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: true },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Leave Balance Sheet",
    code: "LEAVE_BALANCES",
    description: "Opening, earned, used and available per leave type.",
    source: "leave_balances",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      col("leaveType", "Leave type", { width: 16 }),
      num("opening", "Opening"),
      num("allocated", "Allocated"),
      num("carriedForward", "Carried fwd"),
      num("used", "Used"),
      num("pending", "Pending"),
      num("available", "Available"),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Leave Balances", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: false },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Employee Master",
    code: "EMPLOYEE_MASTER",
    description: "The directory with employment details.",
    source: "employees",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("gender", "Gender", { width: 8 }),
      col("dateOfBirth", "Date of birth", { format: "date", width: 12 }),
      col("designation", "Designation", { width: 18 }),
      col("department", "Department", { width: 16 }),
      col("location", "Location", { width: 14 }),
      col("manager", "Reporting to", { width: 20 }),
      col("employmentType", "Type", { width: 12 }),
      col("joiningDate", "Joined", { format: "date", width: 12 }),
      col("workEmail", "Email", { width: 26 }),
      col("phone", "Phone", { width: 14 }),
      col("status", "Status", { width: 10 }),
    ],
    sort: "employeeCode",
    header: { showCompany: true, title: "Employee Master", showPeriod: false, showGeneratedOn: true },
    footer: { showTotals: false },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "CTC Register",
    code: "CTC_REGISTER",
    description: "Current cost to company for every employee, with the salary structure.",
    source: "salary_register",
    columns: [
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("designation", "Designation", { width: 18 }),
      col("department", "Department", { width: 16 }),
      col("structure", "Structure", { width: 16 }),
      col("effectiveFrom", "Effective from", { format: "date", width: 12 }),
      money("ctcMonthly", "Monthly CTC"),
      money("ctcAnnual", "Annual CTC"),
    ],
    sort: "employeeCode",
    groupBy: "department",
    header: { showCompany: true, title: "CTC Register", showPeriod: false, showGeneratedOn: true },
    footer: { showTotals: true },
    page: { orientation: "landscape", size: "A4" },
  },
  {
    name: "Joiners and Leavers",
    code: "JOINERS_LEAVERS",
    description: "Headcount movement in a period.",
    source: "joiners_leavers",
    columns: [
      col("kind", "Joined / Left", { width: 12 }),
      col("date", "Date", { format: "date", width: 12 }),
      col("employeeCode", "Emp code", { width: 12 }),
      col("name", "Name", { width: 24 }),
      col("department", "Department", { width: 16 }),
      col("designation", "Designation", { width: 18 }),
      col("employmentType", "Type", { width: 12 }),
      col("exitType", "Exit type", { width: 12 }),
      num("tenureMonths", "Tenure (months)", { format: "integer" }),
    ],
    sort: "date",
    groupBy: "kind",
    header: { showCompany: true, title: "Joiners and Leavers", showPeriod: true, showGeneratedOn: true },
    footer: { showTotals: false },
    page: { orientation: "landscape", size: "A4" },
  },
];

module.exports = { SHEETS };
