"use strict";

/**
 * Templates seeded into every new organization.
 *
 * They are ordinary DocumentTemplate documents, editable and deletable like
 * any other — they exist so a customer has something working on day one, not
 * as privileged built-ins. The wording is deliberately neutral and generic;
 * every organization is expected to rewrite it in their own voice.
 *
 * Every placeholder used here exists in document.service.buildContext(). A
 * unit test checks that, so a renamed context field breaks a test rather
 * than printing a blank in someone's offer letter.
 */

const ref = (prefix) => ({ enabled: true, prefix, nextNumber: 1, padding: 4 });
const dateLine = (withRef = true) => ({
  type: "paragraph",
  text: withRef ? "Ref: {{document.number}}    Date: {{date.todayFormatted}}" : "Date: {{date.todayFormatted}}",
  style: { align: "right", fontSize: 9 },
});
const addressee = { type: "paragraph", text: "**{{employee.name}}**\n{{employee.designation}}, {{employee.department}}\n{{employee.address}}" };
const signOff = (text = "For {{company.legalName}}") => ({ type: "signature", text: `${text}\n**Authorised Signatory**` });
const employeeSign = { type: "signature", text: "Accepted and agreed\n**{{employee.name}}**", align: "right" };

const TEMPLATES = [
  // ── Hiring ───────────────────────────────────────────────────────────────
  {
    name: "Letter of Intent",
    code: "LETTER_OF_INTENT",
    category: "letter_of_intent",
    contextType: "employee",
    description: "Sent to a candidate before the formal offer, confirming intent to hire.",
    numbering: ref("LOI/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: false },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 12 },
      { type: "heading", text: "Letter of Intent", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "Further to our discussions, {{company.name}} is pleased to confirm its intent to engage you as **{{employee.designation}}** in the {{employee.department}} department, based at {{employee.location}}, with a proposed start date of **{{employee.joiningDateFormatted}}**.",
      },
      {
        type: "paragraph",
        text: "The indicative annual cost to company for this position is **{{salary.ctcAnnualFormatted}}**. A formal letter of appointment setting out the full terms and conditions of employment will follow on completion of pre-employment checks.",
        condition: "salary.ctcAnnual > 0",
      },
      {
        type: "paragraph",
        text: "This letter records our intent and is not itself a contract of employment. It is valid for fourteen days from the date above; please confirm your acceptance in writing within that period.",
      },
      { type: "paragraph", text: "We look forward to working with you." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Offer Letter",
    code: "OFFER_LETTER",
    category: "offer_letter",
    contextType: "employee",
    description: "Sent to a candidate before joining.",
    numbering: ref("OL/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 12 },
      { type: "heading", text: "Letter of Offer", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "We are pleased to offer you the position of **{{employee.designation}}** in our {{employee.department}} department at {{company.name}}. Your appointment will be effective from **{{employee.joiningDateFormatted}}** and you will be based at {{employee.location}}.",
      },
      {
        type: "paragraph",
        text: "Your annual cost to company will be **{{salary.ctcAnnualFormatted}}**, payable monthly in accordance with company policy. A detailed breakdown of your compensation is set out below.",
        condition: "salary.ctcAnnual > 0",
      },
      { type: "spacer", height: 6 },
      {
        type: "key_values",
        rows: [
          { label: "Position", value: "{{employee.designation}}" },
          { label: "Department", value: "{{employee.department}}" },
          { label: "Location", value: "{{employee.location}}" },
          { label: "Date of joining", value: "{{employee.joiningDateFormatted}}" },
          { label: "Employment type", value: "{{employee.employmentType}}" },
          { label: "Probation period", value: "{{employee.probationMonths}} months" },
          { label: "Reporting to", value: "{{employee.manager}}" },
          { label: "Annual CTC", value: "{{salary.ctcAnnualFormatted}}" },
        ],
      },
      { type: "spacer", height: 6 },
      {
        type: "table",
        source: "salary.lines",
        columns: [
          { key: "name", label: "Component", width: 3 },
          { key: "monthly", label: "Monthly", width: 1, align: "right", format: "money", total: true },
          { key: "annual", label: "Annual", width: 1, align: "right", format: "money", total: true },
        ],
        totalsLabel: "Total",
        condition: "salary.ctcAnnual > 0",
      },
      { type: "spacer", height: 8 },
      {
        type: "paragraph",
        text: "This offer is subject to verification of the documents and references you have provided, and to your being free of any obligation that would prevent you taking up this position. Please sign and return a copy of this letter to confirm your acceptance by **{{date.plus7Formatted}}**.",
      },
      { type: "paragraph", text: "We look forward to welcoming you to the team." },
      { type: "spacer", height: 20 },
      { type: "columns", left: "For **{{company.legalName}}**\n\n\n\n________________________\nAuthorised Signatory", right: "Accepted\n\n\n\n________________________\n{{employee.name}}\nDate: __________" },
    ],
  },

  {
    name: "Appointment Letter",
    code: "APPOINTMENT_LETTER",
    category: "appointment_letter",
    contextType: "employee",
    description: "The formal terms of employment, issued on joining.",
    numbering: ref("AL/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Letter of Appointment", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "With reference to your application and the subsequent discussions, we are pleased to appoint you as **{{employee.designation}}** at {{company.name}} with effect from **{{employee.joiningDateFormatted}}**, on the following terms.",
      },
      { type: "spacer", height: 6 },
      {
        type: "key_values",
        rows: [
          { label: "Employee code", value: "{{employee.employeeCode}}" },
          { label: "Designation", value: "{{employee.designation}}" },
          { label: "Department", value: "{{employee.department}}" },
          { label: "Reporting to", value: "{{employee.manager}}" },
          { label: "Place of posting", value: "{{employee.location}}" },
          { label: "Date of joining", value: "{{employee.joiningDateFormatted}}" },
          { label: "Probation", value: "{{employee.probationMonths}} months, until {{employee.probationEndsFormatted}}" },
          { label: "Notice period", value: "{{employee.noticePeriodDays}} days" },
        ],
      },
      { type: "spacer", height: 6 },
      { type: "heading", text: "Terms and conditions", level: 2 },
      {
        type: "list",
        items: [
          "**Probation.** You will be on probation for {{employee.probationMonths}} months from your date of joining. Confirmation will be communicated in writing; until then either party may end the engagement with seven days' notice.",
          "**Hours of work.** You will observe the working hours and holidays applicable to your location, as notified from time to time.",
          "**Compensation.** Your remuneration is set out in the annexure to this letter and is subject to statutory deductions.",
          "**Notice.** After confirmation, either party may terminate this appointment by giving {{employee.noticePeriodDays}} days' notice in writing, or salary in lieu.",
          "**Confidentiality.** You will keep confidential all information relating to the business of {{company.name}} and its clients, during and after your employment.",
          "**Policies.** Your employment is governed by the policies of {{company.name}} as amended from time to time, which form part of these terms.",
        ],
      },
      { type: "spacer", height: 10 },
      { type: "paragraph", text: "Please sign the duplicate copy of this letter as a token of your acceptance." },
      { type: "spacer", height: 16 },
      { type: "columns", left: "For **{{company.legalName}}**\n\n\n\n________________________\nAuthorised Signatory", right: "Accepted\n\n\n\n________________________\n{{employee.name}}\nDate: __________" },
    ],
  },

  // ── Probation and confirmation ───────────────────────────────────────────
  {
    name: "Confirmation Letter",
    code: "CONFIRMATION_LETTER",
    category: "confirmation_letter",
    contextType: "employee",
    description: "Confirms employment at the end of probation.",
    numbering: ref("CL/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Confirmation of Employment", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "We are pleased to inform you that, following a review of your performance during the probation period, your services with {{company.name}} are **confirmed with effect from {{employee.confirmationDateFormatted}}** in the position of {{employee.designation}}.",
      },
      { type: "paragraph", text: "All other terms of your appointment remain unchanged. Congratulations, and we look forward to your continued contribution." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Probation Extension Letter",
    code: "PROBATION_EXTENSION",
    category: "probation_extension",
    contextType: "employee",
    description: "Extends probation with a reason and a new review date.",
    numbering: ref("PE/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Extension of Probation", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "Your probation period, due to end on {{employee.probationEndsFormatted}}, has been reviewed. We have decided to **extend it by a further period**, during which your performance will be reviewed again against the expectations discussed with you.",
      },
      { type: "paragraph", text: "The specific areas for improvement and the support that will be provided have been shared with you separately by your reporting manager. All other terms of your appointment remain unchanged." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  // ── Movement and reward ──────────────────────────────────────────────────
  {
    name: "Increment Letter",
    code: "INCREMENT_LETTER",
    category: "increment_letter",
    contextType: "employee",
    description: "Communicates a salary revision.",
    numbering: ref("INC/"),
    storeAs: { category: "salary", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Salary Revision", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "In recognition of your performance and contribution, we are pleased to inform you that your compensation has been revised with effect from **{{salary.effectiveFromFormatted}}**.",
      },
      {
        type: "key_values",
        rows: [
          { label: "Revised annual CTC", value: "{{salary.ctcAnnualFormatted}}" },
          { label: "Revised monthly CTC", value: "{{salary.ctcMonthlyFormatted}}" },
          { label: "Effective from", value: "{{salary.effectiveFromFormatted}}" },
          { label: "Designation", value: "{{employee.designation}}" },
        ],
      },
      {
        type: "table",
        source: "salary.lines",
        columns: [
          { key: "name", label: "Component", width: 3 },
          { key: "monthly", label: "Monthly", width: 1, align: "right", format: "money", total: true },
          { key: "annual", label: "Annual", width: 1, align: "right", format: "money", total: true },
        ],
      },
      { type: "paragraph", text: "All other terms of your employment remain unchanged. We thank you for your continued commitment." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Promotion Letter",
    code: "PROMOTION_LETTER",
    category: "promotion_letter",
    contextType: "employee",
    description: "Announces a promotion and the revised terms.",
    numbering: ref("PR/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Promotion", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "We are delighted to inform you that you have been promoted to **{{employee.designation}}** in the {{employee.department}} department with effect from **{{date.todayFormatted}}**. This promotion recognises the results you have delivered and the way you have delivered them.",
      },
      {
        type: "paragraph",
        text: "Your revised annual cost to company will be **{{salary.ctcAnnualFormatted}}**, effective {{salary.effectiveFromFormatted}}.",
        condition: "salary.ctcAnnual > 0",
      },
      { type: "paragraph", text: "You will report to {{employee.manager}}. All other terms of your employment remain unchanged. Congratulations." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Transfer Letter",
    code: "TRANSFER_LETTER",
    category: "transfer_letter",
    contextType: "employee",
    description: "Records a move to a new location, department or reporting line.",
    numbering: ref("TR/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Transfer", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "This is to inform you that you are being transferred to **{{employee.location}}**, {{employee.department}} department, with effect from **{{date.todayFormatted}}**. You will report to {{employee.manager}} in your new role as {{employee.designation}}.",
      },
      { type: "paragraph", text: "Your compensation and other terms of employment remain unchanged. Please complete the handover of your current responsibilities before the effective date and report to your new location on that day." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Appraisal Letter",
    code: "APPRAISAL_LETTER",
    category: "appraisal_letter",
    contextType: "employee",
    description: "Summarises the annual review outcome.",
    numbering: ref("AP/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Performance Review — {{date.financialYear}}", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "Thank you for your contribution over the review period. Following the discussions with your reporting manager, the outcome of your performance review is summarised below." },
      {
        type: "key_values",
        layout: "single",
        rows: [
          { label: "Review period", value: "{{date.financialYear}}" },
          { label: "Designation", value: "{{employee.designation}}" },
          { label: "Reporting manager", value: "{{employee.manager}}" },
          { label: "Revised annual CTC", value: "{{salary.ctcAnnualFormatted}}" },
          { label: "Effective from", value: "{{salary.effectiveFromFormatted}}" },
        ],
      },
      { type: "paragraph", text: "The goals and development plan for the coming period have been agreed with you and recorded separately. We look forward to your continued growth with {{company.name}}." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Contract Extension",
    code: "CONTRACT_EXTENSION",
    category: "contract_extension",
    contextType: "employee",
    description: "Extends a fixed-term or contract engagement.",
    numbering: ref("CE/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Extension of Engagement", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      {
        type: "paragraph",
        text: "We are pleased to extend your engagement as **{{employee.designation}}** with {{company.name}}. The extended term begins on **{{date.todayFormatted}}** and continues on the same terms and conditions as your existing agreement, except as noted below.",
      },
      { type: "key_values", rows: [{ label: "Engagement type", value: "{{employee.employmentType}}" }, { label: "Location", value: "{{employee.location}}" }, { label: "Reporting to", value: "{{employee.manager}}" }, { label: "Annual CTC", value: "{{salary.ctcAnnualFormatted}}" }] },
      { type: "paragraph", text: "Please countersign to confirm your acceptance." },
      { type: "spacer", height: 16 },
      { type: "columns", left: "For **{{company.legalName}}**\n\n\n\n________________________\nAuthorised Signatory", right: "Accepted\n\n\n\n________________________\n{{employee.name}}" },
    ],
  },

  // ── Discipline ───────────────────────────────────────────────────────────
  {
    name: "Warning Letter",
    code: "WARNING_LETTER",
    category: "warning_letter",
    contextType: "employee",
    numbering: ref("WL/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Letter of Warning", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "This letter is to formally record our concern regarding the matter discussed with you on the date noted above. We expect an immediate and sustained improvement." },
      { type: "paragraph", text: "Please treat this as a **formal warning**. Any recurrence may lead to further disciplinary action in accordance with company policy, up to and including termination of employment." },
      { type: "paragraph", text: "A copy of this letter will be placed on your personnel file. Please acknowledge receipt." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Show Cause Notice",
    code: "SHOW_CAUSE",
    category: "show_cause_notice",
    contextType: "employee",
    description: "Asks the employee to explain conduct before any decision is taken.",
    numbering: ref("SCN/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Show Cause Notice", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "It has been brought to our notice that you have acted in a manner contrary to the policies of {{company.name}}, as set out in the particulars communicated to you. Such conduct, if established, constitutes misconduct under the terms of your employment." },
      { type: "paragraph", text: "You are hereby called upon to **show cause in writing within seven days** of receipt of this notice why disciplinary action should not be taken against you. Should no explanation be received within that period, it will be presumed that you have none to offer and the matter will be decided on the material available." },
      { type: "paragraph", text: "This notice is issued without prejudice to any further action the company may take." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Termination Letter",
    code: "TERMINATION_LETTER",
    category: "termination_letter",
    contextType: "exit",
    description: "Ends employment at the initiative of the company.",
    numbering: ref("TL/"),
    storeAs: { category: "employment", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Termination of Employment", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "This letter confirms that your employment with {{company.name}} as {{employee.designation}} is terminated with effect from **{{employee.lastWorkingDayFormatted}}**, in accordance with the terms of your appointment." },
      { type: "paragraph", text: "Your final settlement, including salary up to the last working day, any leave encashment due, and recoveries where applicable, will be processed in accordance with company policy and paid to your registered bank account." },
      { type: "paragraph", text: "You are required to return all company property in your possession and complete the exit formalities before your last working day. Your obligations of confidentiality continue after your employment ends." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  // ── Leaving ──────────────────────────────────────────────────────────────
  {
    name: "Resignation Acceptance",
    code: "RESIGNATION_ACCEPTANCE",
    category: "resignation_acceptance",
    contextType: "exit",
    description: "Accepts a resignation and confirms the last working day.",
    numbering: ref("RA/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Acceptance of Resignation", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "We acknowledge receipt of your resignation dated **{{employee.resignationDateFormatted}}** from the position of {{employee.designation}}, and confirm that it has been accepted." },
      { type: "paragraph", text: "Your last working day will be **{{employee.lastWorkingDayFormatted}}**, on completion of your notice period of {{employee.noticePeriodDays}} days. Please complete the handover of your responsibilities and the exit formalities before that date. Your full and final settlement will be processed thereafter." },
      { type: "paragraph", text: "We thank you for your contribution to {{company.name}} and wish you every success." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Relieving Letter",
    code: "RELIEVING_LETTER",
    category: "relieving_letter",
    contextType: "exit",
    numbering: ref("RL/"),
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Relieving Letter", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "This is to confirm that your resignation has been accepted and that you have been relieved from your duties as **{{employee.designation}}** at {{company.name}} with effect from the close of business on **{{employee.lastWorkingDayFormatted}}**." },
      { type: "paragraph", text: "All company property in your possession has been returned and your dues have been settled in accordance with company policy." },
      { type: "paragraph", text: "We thank you for your contribution and wish you well in your future endeavours." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "Experience Certificate",
    code: "EXPERIENCE_CERTIFICATE",
    category: "experience_certificate",
    contextType: "exit",
    numbering: ref("EXP/"),
    storeAs: { category: "certificate", visibleToEmployee: true },
    footer: { enabled: true, text: "", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "To Whomsoever It May Concern", style: { align: "center" } },
      { type: "spacer", height: 14 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}** (Employee Code: {{employee.employeeCode}}) was employed with {{company.legalName}} from **{{employee.joiningDateFormatted}}** to **{{employee.lastWorkingDayFormatted}}**, a period of {{employee.tenure}}.", style: { align: "justify" } },
      { type: "paragraph", text: "At the time of leaving, {{employee.firstName}} held the position of **{{employee.designation}}** in the {{employee.department}} department.", style: { align: "justify" } },
      { type: "paragraph", text: "We found {{employee.firstName}} to be sincere and diligent in the discharge of duties. We wish them every success in their future endeavours.", style: { align: "justify" } },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "Full and Final Settlement Statement",
    code: "FNF_STATEMENT",
    category: "full_final_settlement",
    contextType: "exit",
    description: "The closing account: dues, recoveries and the net payable.",
    numbering: ref("FNF/"),
    storeAs: { category: "salary", visibleToEmployee: true, requireAcknowledgement: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 10 },
      { type: "heading", text: "Full and Final Settlement", style: { align: "center" } },
      { type: "spacer", height: 8 },
      {
        type: "key_values",
        rows: [
          { label: "Employee", value: "{{employee.name}} ({{employee.employeeCode}})" },
          { label: "Designation", value: "{{employee.designation}}" },
          { label: "Department", value: "{{employee.department}}" },
          { label: "Date of joining", value: "{{employee.joiningDateFormatted}}" },
          { label: "Last working day", value: "{{employee.lastWorkingDayFormatted}}" },
          { label: "Exit type", value: "{{employee.exitType}}" },
        ],
      },
      { type: "heading", text: "Dues payable", level: 2 },
      {
        type: "table",
        source: "settlement.dues",
        columns: [
          { key: "label", label: "Item", width: 3 },
          { key: "detail", label: "Basis", width: 2 },
          { key: "amount", label: "Amount", width: 1, align: "right", format: "money", total: true },
        ],
        emptyText: "No dues recorded.",
      },
      { type: "heading", text: "Recoveries", level: 2 },
      {
        type: "table",
        source: "settlement.recoveries",
        columns: [
          { key: "label", label: "Item", width: 3 },
          { key: "detail", label: "Basis", width: 2 },
          { key: "amount", label: "Amount", width: 1, align: "right", format: "money", total: true },
        ],
        emptyText: "No recoveries.",
      },
      { type: "divider" },
      {
        type: "key_values",
        layout: "single",
        inline: true,
        rows: [
          { label: "Total dues", value: "{{settlement.totalDuesFormatted}}" },
          { label: "Total recoveries", value: "{{settlement.totalRecoveriesFormatted}}" },
          { label: "Net payable", value: "{{settlement.netFormatted}}" },
        ],
      },
      { type: "spacer", height: 10 },
      { type: "paragraph", text: "The above amount will be paid to the registered bank account ending {{employee.bankAccountLast4}}. This settlement is in full discharge of all claims arising from the employment.", style: { fontSize: 9 } },
      { type: "spacer", height: 16 },
      { type: "columns", left: "Prepared by\n\n\n________________________\nPayroll", right: "Received and accepted\n\n\n________________________\n{{employee.name}}" },
    ],
  },

  // ── Certificates and proofs ──────────────────────────────────────────────
  {
    name: "Payslip",
    code: "PAYSLIP",
    category: "salary_slip",
    contextType: "payslip",
    storeAs: { category: "salary", visibleToEmployee: true },
    footer: { enabled: true, text: "This is a computer-generated payslip and does not require a signature.", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: true },
    blocks: [
      { type: "heading", text: "Payslip for {{payslip.period}}", style: { align: "center" } },
      { type: "spacer", height: 8 },
      {
        type: "key_values",
        rows: [
          { label: "Employee name", value: "{{employee.name}}" },
          { label: "Employee code", value: "{{employee.employeeCode}}" },
          { label: "Designation", value: "{{employee.designation}}" },
          { label: "Department", value: "{{employee.department}}" },
          { label: "Date of joining", value: "{{employee.joiningDateFormatted}}" },
          { label: "Payslip number", value: "{{payslip.number}}" },
          { label: "Bank account", value: "{{employee.bankName}} ····{{employee.bankAccountLast4}}" },
          { label: "UAN / PF", value: "{{employee.uan}} / {{employee.pfNumber}}" },
        ],
      },
      { type: "divider" },
      { type: "heading", text: "Attendance", level: 2 },
      {
        type: "key_values",
        rows: [
          { label: "Days in period", value: "{{payslip.attendance.totalDays}}" },
          { label: "Payable days", value: "{{payslip.attendance.payableDays}}" },
          { label: "Loss of pay days", value: "{{payslip.attendance.lossOfPayDays}}" },
          { label: "Paid leave", value: "{{payslip.attendance.paidLeaveDays}}" },
        ],
      },
      { type: "spacer", height: 6 },
      { type: "columns", left: "**Earnings**", right: "**Deductions**" },
      {
        type: "table",
        source: "payslip.earnings",
        columns: [
          { key: "name", label: "Earning", width: 3 },
          { key: "amount", label: "Amount", width: 1, align: "right" },
        ],
      },
      {
        type: "table",
        source: "payslip.deductionLines",
        columns: [
          { key: "name", label: "Deduction", width: 3 },
          { key: "amount", label: "Amount", width: 1, align: "right" },
        ],
        emptyText: "No deductions.",
      },
      { type: "divider" },
      {
        type: "key_values",
        rows: [
          { label: "Gross earnings", value: "{{payslip.grossFormatted}}" },
          { label: "Total deductions", value: "{{payslip.deductionsFormatted}}" },
          { label: "Net payable", value: "{{payslip.netFormatted}}" },
          { label: "Net in words", value: "{{payslip.netInWords}}" },
        ],
      },
    ],
  },

  {
    name: "Salary Certificate",
    code: "SALARY_CERTIFICATE",
    category: "salary_certificate",
    contextType: "employee",
    numbering: ref("SC/"),
    storeAs: { category: "salary", visibleToEmployee: true },
    footer: { enabled: true, text: "", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "Salary Certificate", style: { align: "center" } },
      { type: "spacer", height: 12 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}** (Employee Code: {{employee.employeeCode}}) is employed with {{company.legalName}} as **{{employee.designation}}** since {{employee.joiningDateFormatted}}.", style: { align: "justify" } },
      { type: "paragraph", text: "Their present annual cost to company is **{{salary.ctcAnnualFormatted}}**, equivalent to {{salary.ctcMonthlyFormatted}} per month, made up as follows.", style: { align: "justify" } },
      {
        type: "table",
        source: "salary.lines",
        columns: [
          { key: "name", label: "Component", width: 3 },
          { key: "monthly", label: "Monthly", width: 1, align: "right", format: "money", total: true },
          { key: "annual", label: "Annual", width: 1, align: "right", format: "money", total: true },
        ],
      },
      { type: "paragraph", text: "This certificate has been issued at the request of the employee for the purpose stated by them, and does not constitute a guarantee of any kind." },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "Salary Annexure",
    code: "SALARY_ANNEXURE",
    category: "salary_annexure",
    contextType: "employee",
    description: "The compensation breakdown attached to an offer or appointment.",
    storeAs: { category: "salary", visibleToEmployee: true },
    blocks: [
      { type: "heading", text: "Annexure — Compensation Structure", style: { align: "center" } },
      { type: "spacer", height: 6 },
      { type: "key_values", rows: [{ label: "Employee", value: "{{employee.name}}" }, { label: "Designation", value: "{{employee.designation}}" }, { label: "Effective from", value: "{{salary.effectiveFromFormatted}}" }, { label: "Salary structure", value: "{{salary.structure}}" }] },
      {
        type: "table",
        source: "salary.lines",
        zebra: true,
        columns: [
          { key: "name", label: "Component", width: 3 },
          { key: "type", label: "Type", width: 1.2 },
          { key: "monthly", label: "Monthly", width: 1, align: "right", format: "money", total: true },
          { key: "annual", label: "Annual", width: 1, align: "right", format: "money", total: true },
        ],
        totalsLabel: "Cost to company",
      },
      { type: "paragraph", text: "Statutory deductions and taxes are applied as per the prevailing law. Reimbursements are paid against valid claims. This annexure forms part of the letter it accompanies.", style: { fontSize: 9 } },
    ],
  },

  {
    name: "Bonafide Certificate",
    code: "BONAFIDE",
    category: "bonafide_certificate",
    contextType: "employee",
    description: "Confirms employment for a bank, embassy or landlord.",
    numbering: ref("BC/"),
    storeAs: { category: "certificate", visibleToEmployee: true },
    footer: { enabled: true, text: "", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "Bonafide Certificate", style: { align: "center" } },
      { type: "spacer", height: 12 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}**, {{employee.gender}}, is a bonafide employee of {{company.legalName}}, working as **{{employee.designation}}** in the {{employee.department}} department since **{{employee.joiningDateFormatted}}** (Employee Code: {{employee.employeeCode}}).", style: { align: "justify" } },
      { type: "paragraph", text: "{{employee.firstName}} is a {{employee.employmentType}} employee and is presently posted at our {{employee.location}} office.", style: { align: "justify" } },
      { type: "paragraph", text: "This certificate is issued at the request of the employee for the purpose stated by them and is not valid for any other purpose.", style: { align: "justify" } },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "Address Proof Letter",
    code: "ADDRESS_PROOF",
    category: "address_proof",
    contextType: "employee",
    numbering: ref("ADP/"),
    storeAs: { category: "certificate", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "To Whomsoever It May Concern", style: { align: "center" } },
      { type: "spacer", height: 12 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}** (Employee Code: {{employee.employeeCode}}) is employed with {{company.legalName}} as {{employee.designation}}, and that the residential address on our records is:", style: { align: "justify" } },
      { type: "spacer", height: 4 },
      { type: "paragraph", text: "**{{employee.address}}**", style: { align: "center" } },
      { type: "spacer", height: 4 },
      { type: "paragraph", text: "This letter is issued at the request of the employee for the purpose of address verification and does not constitute a guarantee.", style: { align: "justify" } },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "No Objection Certificate",
    code: "NOC",
    category: "no_objection_certificate",
    contextType: "employee",
    description: "States that the company has no objection to a stated purpose — travel, study, a visa.",
    numbering: ref("NOC/"),
    storeAs: { category: "certificate", visibleToEmployee: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "No Objection Certificate", style: { align: "center" } },
      { type: "spacer", height: 12 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}** (Employee Code: {{employee.employeeCode}}) has been employed with {{company.legalName}} as {{employee.designation}} since {{employee.joiningDateFormatted}}.", style: { align: "justify" } },
      { type: "paragraph", text: "{{company.name}} has **no objection** to {{employee.firstName}} pursuing the purpose stated in their request, provided it does not interfere with their duties and responsibilities towards the company.", style: { align: "justify" } },
      { type: "paragraph", text: "This certificate is issued at the request of the employee and does not create any obligation on the part of the company.", style: { align: "justify" } },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "Internship Certificate",
    code: "INTERNSHIP_CERTIFICATE",
    category: "internship_certificate",
    contextType: "exit",
    numbering: ref("IC/"),
    storeAs: { category: "certificate", visibleToEmployee: true },
    footer: { enabled: true, text: "", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: true },
    blocks: [
      dateLine(),
      { type: "spacer", height: 16 },
      { type: "heading", text: "Certificate of Internship", style: { align: "center" } },
      { type: "spacer", height: 12 },
      { type: "paragraph", text: "This is to certify that **{{employee.name}}** successfully completed an internship with {{company.legalName}} in the {{employee.department}} department from **{{employee.joiningDateFormatted}}** to **{{employee.lastWorkingDayFormatted}}**, under the supervision of {{employee.manager}}.", style: { align: "justify" } },
      { type: "paragraph", text: "During this period {{employee.firstName}} worked on assignments relevant to the role of {{employee.designation}} and demonstrated commitment, curiosity and a willingness to learn.", style: { align: "justify" } },
      { type: "paragraph", text: "We wish {{employee.firstName}} the very best for the future." },
      { type: "spacer", height: 24 },
      signOff(),
    ],
  },

  {
    name: "Training Certificate",
    code: "TRAINING_CERTIFICATE",
    category: "training_certificate",
    contextType: "employee",
    storeAs: { category: "certificate", visibleToEmployee: true },
    page: { size: "A4", orientation: "landscape", margins: { top: 70, bottom: 60, left: 70, right: 70 } },
    blocks: [
      { type: "spacer", height: 20 },
      { type: "heading", text: "Certificate of Completion", style: { align: "center", fontSize: 24 } },
      { type: "spacer", height: 16 },
      { type: "paragraph", text: "This certificate is proudly presented to", style: { align: "center", fontSize: 11 } },
      { type: "spacer", height: 6 },
      { type: "heading", text: "{{employee.name}}", style: { align: "center", fontSize: 20 } },
      { type: "spacer", height: 6 },
      { type: "paragraph", text: "for successfully completing the training programme conducted by {{company.name}}.", style: { align: "center", fontSize: 11 } },
      { type: "spacer", height: 30 },
      { type: "columns", left: "________________________\nTrainer", right: "________________________\nAuthorised Signatory" },
      { type: "spacer", height: 10 },
      { type: "paragraph", text: "{{date.todayFormatted}}", style: { align: "center", fontSize: 9 } },
    ],
  },

  {
    name: "Leave Approval Letter",
    code: "LEAVE_APPROVAL",
    category: "leave_approval",
    contextType: "leave_request",
    storeAs: { category: "employment", visibleToEmployee: true },
    blocks: [
      dateLine(false),
      { type: "spacer", height: 12 },
      addressee,
      { type: "spacer", height: 10 },
      { type: "heading", text: "Leave Approval", style: { align: "center" } },
      { type: "spacer", height: 8 },
      { type: "paragraph", text: "Dear {{employee.firstName}}," },
      { type: "paragraph", text: "Your application for **{{leave.type}}** from **{{leave.fromFormatted}}** to **{{leave.toFormatted}}** ({{leave.days}} day(s)) has been **{{leave.status}}**." },
      { type: "key_values", rows: [{ label: "Leave type", value: "{{leave.type}}" }, { label: "From", value: "{{leave.fromFormatted}}" }, { label: "To", value: "{{leave.toFormatted}}" }, { label: "Days", value: "{{leave.days}}" }, { label: "Reason", value: "{{leave.reason}}" }] },
      { type: "paragraph", text: "Please ensure your responsibilities are handed over before you go. We wish you a restful break." },
      { type: "spacer", height: 20 },
      signOff(),
    ],
  },

  {
    name: "ID Card",
    code: "ID_CARD",
    category: "id_card",
    contextType: "employee",
    description: "A wallet-sized card; print two per A4 and cut.",
    page: { size: "A4", orientation: "portrait", margins: { top: 40, bottom: 40, left: 40, right: 40 } },
    header: { enabled: true, showLogo: true, showCompanyName: true, showAddress: false, showContact: false, text: "" },
    footer: { enabled: false, text: "", showPageNumbers: false, showGeneratedOn: false, showVerificationQr: false },
    blocks: [
      { type: "heading", text: "Employee Identity Card", style: { align: "center" } },
      { type: "spacer", height: 8 },
      {
        type: "key_values",
        layout: "single",
        inline: true,
        rows: [
          { label: "Name", value: "{{employee.name}}" },
          { label: "Employee code", value: "{{employee.employeeCode}}" },
          { label: "Designation", value: "{{employee.designation}}" },
          { label: "Department", value: "{{employee.department}}" },
          { label: "Location", value: "{{employee.location}}" },
          { label: "Blood group", value: "{{employee.bloodGroup}}" },
          { label: "Emergency contact", value: "{{employee.emergencyContact}}" },
          { label: "Valid from", value: "{{employee.joiningDateFormatted}}" },
        ],
      },
      { type: "spacer", height: 8 },
      { type: "qr", text: "Scan to verify", height: 64 },
      { type: "spacer", height: 6 },
      { type: "paragraph", text: "This card is the property of {{company.legalName}} and must be returned on leaving. If found, please return to {{company.addressLine}}.", style: { fontSize: 7.5, align: "center" } },
    ],
  },

  // ── Checklists ───────────────────────────────────────────────────────────
  {
    name: "Joining Checklist",
    code: "JOINING_CHECKLIST",
    category: "joining_checklist",
    contextType: "employee",
    description: "What to collect and set up on day one.",
    storeAs: { category: "employment", visibleToEmployee: false },
    blocks: [
      { type: "heading", text: "Joining Checklist — {{employee.name}}", style: { align: "left" } },
      { type: "key_values", rows: [{ label: "Employee code", value: "{{employee.employeeCode}}" }, { label: "Joining date", value: "{{employee.joiningDateFormatted}}" }, { label: "Department", value: "{{employee.department}}" }, { label: "Reporting to", value: "{{employee.manager}}" }] },
      { type: "heading", text: "Documents to collect", level: 2 },
      { type: "checklist", items: ["Signed appointment letter", "Identity proof (PAN / Aadhaar / passport)", "Address proof", "Educational certificates", "Previous employment relieving letter and last payslips", "Bank account details and cancelled cheque", "Passport-size photographs", "PF / UAN details and Form 11", "Nomination forms (PF, gratuity, ESI)"] },
      { type: "heading", text: "Set-up", level: 2 },
      { type: "checklist", items: ["Employee code and biometric enrolment", "Email account and system access", "Laptop / equipment issued and recorded", "ID card issued", "Added to payroll with salary structure", "Leave policy and shift assigned", "Introduced to team and buddy assigned", "Policies acknowledged in the portal"] },
      { type: "spacer", height: 16 },
      { type: "columns", left: "________________________\nHR", right: "________________________\nEmployee" },
    ],
  },

  {
    name: "Exit Checklist",
    code: "EXIT_CHECKLIST",
    category: "exit_checklist",
    contextType: "exit",
    description: "Clearance before the last working day.",
    storeAs: { category: "employment", visibleToEmployee: false },
    blocks: [
      { type: "heading", text: "Exit Clearance — {{employee.name}}" },
      { type: "key_values", rows: [{ label: "Employee code", value: "{{employee.employeeCode}}" }, { label: "Last working day", value: "{{employee.lastWorkingDayFormatted}}" }, { label: "Department", value: "{{employee.department}}" }, { label: "Exit type", value: "{{employee.exitType}}" }] },
      { type: "heading", text: "Returns", level: 2 },
      { type: "checklist", items: ["Laptop, charger and accessories", "ID card and access cards", "Mobile phone / SIM", "Keys and any other company property", "Company documents and data handed over"] },
      { type: "heading", text: "Clearances", level: 2 },
      { type: "checklist", items: ["Reporting manager — handover complete", "IT — accounts disabled, equipment received", "Finance — advances and loans settled", "Admin — assets returned", "HR — exit interview done, documents issued"] },
      { type: "heading", text: "Documents to issue", level: 2 },
      { type: "checklist", items: ["Resignation acceptance", "Relieving letter", "Experience certificate", "Full and final settlement statement", "Form 16 / tax documents"] },
      { type: "spacer", height: 16 },
      { type: "columns", left: "________________________\nHR", right: "________________________\nEmployee" },
    ],
  },
];

module.exports = { TEMPLATES };
