"use strict";

const { expandPermissions } = require("./permissions");

/**
 * System role templates.
 *
 * These are seeded into every new organization as editable Role documents.
 * A tenant can rename them, change their permissions, or add roles of their
 * own; the platform never reads role NAMES to make a decision, only the
 * permissions attached to them. The one exception is `isOwner`, which protects
 * the last administrator from locking themselves out.
 */
const SYSTEM_ROLES = [
  {
    key: "TENANT_OWNER",
    name: "Owner",
    description: "Full control of the organization, including billing and security.",
    isOwner: true,
    isSystem: true,
    rank: 10,
    permissions: ["*"],
  },
  {
    key: "HR_ADMIN",
    name: "HR Admin",
    description: "Runs the HR function end to end.",
    isSystem: true,
    rank: 20,
    permissions: [
      "dashboard.*",
      "employee.*",
      "department.*",
      "designation.*",
      "location.*",
      "attendance.*",
      "shift.*",
      "holiday.*",
      "leave.*",
      "document.*",
      "workflow.*",
      "report.*",
      "biometric.*",
      "notification.*",
      "audit.view",
      "user.view",
      "user.invite",
      "user.update",
      "role.view",
      "role.assign",
      "settings.view",
      "settings.manage",
      "settings.manage_branding",
      "settings.manage_policies",
      "profile.view_own",
      "profile.update_own",
      "asset.*",
      "expense.approve",
    ],
  },
  {
    key: "HR_MANAGER",
    name: "HR Manager",
    description: "Day-to-day HR operations without settings or payroll access.",
    isSystem: true,
    rank: 30,
    permissions: [
      "dashboard.view",
      "dashboard.view_org_wide",
      "employee.view",
      "employee.create",
      "employee.update",
      "employee.export",
      "department.view",
      "designation.view",
      "location.view",
      "attendance.view",
      "attendance.manage",
      "attendance.correct",
      "attendance.approve",
      "attendance.export",
      "shift.view",
      "shift.assign",
      "holiday.view",
      "leave.view",
      "leave.approve",
      "leave.reject",
      "leave.apply_on_behalf",
      "leave.export",
      "document.view",
      "document.upload",
      "document.generate",
      "workflow.view",
      "workflow.act",
      "report.view",
      "report.export",
      "profile.view_own",
      "profile.update_own",
    ],
  },
  {
    key: "MANAGER",
    name: "Manager",
    description: "Manages a team: approvals and team visibility only.",
    isSystem: true,
    rank: 40,
    permissions: [
      "dashboard.view",
      "employee.view",
      "attendance.view_team",
      "attendance.view_own",
      "attendance.correct",
      "attendance.approve",
      "attendance.punch",
      "leave.view_team",
      "leave.apply",
      "leave.approve",
      "leave.reject",
      "workflow.view",
      "workflow.act",
      "workflow.delegate",
      "report.view",
      "document.view_own",
      "profile.view_own",
      "profile.update_own",
      "payroll.view_own_payslip",
      "expense.submit",
      "expense.view_own",
      "expense.approve",
      "asset.view",
      "holiday.view",
      "shift.view",
    ],
  },
  {
    key: "PAYROLL_ADMIN",
    name: "Payroll Admin",
    description: "Owns salary structures, payroll runs and payslips.",
    isSystem: true,
    rank: 35,
    permissions: [
      "dashboard.view",
      "employee.view",
      "employee.view_sensitive",
      "attendance.view",
      "attendance.export",
      "leave.view",
      "payroll.*",
      "report.view",
      "report.export",
      "document.view",
      "document.generate",
      "audit.view",
      "profile.view_own",
      "profile.update_own",
    ],
  },
  {
    key: "ACCOUNTANT",
    name: "Accountant",
    description: "Read access to payroll output and financial reports.",
    isSystem: true,
    rank: 50,
    permissions: [
      "dashboard.view",
      "employee.view",
      "payroll.view",
      "payroll.export",
      "report.view",
      "report.export",
      "expense.approve",
      "profile.view_own",
      "profile.update_own",
    ],
  },
  {
    key: "RECRUITER",
    name: "Recruiter",
    description: "Onboards new employees.",
    isSystem: true,
    rank: 55,
    permissions: [
      "dashboard.view",
      "employee.view",
      "employee.create",
      "employee.update",
      "employee.import",
      "department.view",
      "designation.view",
      "location.view",
      "document.view",
      "document.upload",
      "document.generate",
      "profile.view_own",
      "profile.update_own",
    ],
  },
  {
    key: "EMPLOYEE",
    name: "Employee",
    description: "Self-service access only.",
    isSystem: true,
    isDefault: true,
    rank: 90,
    permissions: [
      "dashboard.view",
      "attendance.view_own",
      "attendance.punch",
      "attendance.correct",
      "leave.apply",
      "leave.view",
      "payroll.view_own_payslip",
      "document.view_own",
      "profile.view_own",
      "profile.update_own",
      "expense.submit",
      "expense.view_own",
      "asset.view",
      "holiday.view",
      "shift.view",
      "workflow.view",
    ],
  },
];

/** Platform-level roles. These never live inside a tenant. */
const PLATFORM_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  SUPPORT: "SUPPORT",
};

function systemRoleDefinitions() {
  return SYSTEM_ROLES.map((role) => ({
    ...role,
    permissions: expandPermissions(role.permissions),
  }));
}

module.exports = { SYSTEM_ROLES, PLATFORM_ROLES, systemRoleDefinitions };
